In [307]:
#importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [308]:
#loading the data in DataFrame

customers_raw = pd.read_csv("DimCustomers_dirty.csv")#cleaned
orders_raw = pd.read_csv("FactOrders_dirty.csv")#cleaned
sales_raw = pd.read_csv("FactSales_dirty.csv")#cleaned

products_raw = pd.read_csv("DimProducts_dirty.csv")

In [309]:
#making copies before cleaning

customers = customers_raw.copy()
orders = orders_raw.copy()
sales = sales_raw.copy()
products = products_raw.copy()

In [310]:
#printing rows and column numbers for each dataframe

print("="*50)
print("Total Rows and Columns in Each DataFrame")
print("="*50)
print("Customer Dataframe",customers.shape)
print("Order Dataframe",orders.shape)
print("Sales Dataframe",sales.shape)
print("Products Dataframe",products.shape)

==================================================
Total Rows and Columns in Each DataFrame
==================================================
Customer Dataframe (12120, 9)
Order Dataframe (32320, 7)
Sales Dataframe (100000, 12)
Products Dataframe (2030, 8)

In [311]:
customers.head()

,CustomerID,Name,Gender,Age,City,State,SignupDate,Segment,Acquisition
0,C000001,Aditi Sharma,Male,46,Guwahati,Assam,2023-12-19,Consumer,Organic Search
1,C000002,Aditya Rao,Male,18,Ahmedabad,Gujarat,2023-12-29,Consumer,Organic Search
2,C000003,Arjun Reddy,Male,20,Mumbai,Maharashtra,2025-02-11,Consumer,Referral
3,C000004,Sanya Kumar,Female,26,Mysuru,Karnataka,2026-04-27,Small Business,Paid Search
4,C000005,Aarav Rao,Female,30,Chennai,Tamil Nadu,2024-05-25,Consumer,Email

In [312]:
customers.tail()

,CustomerID,Name,Gender,Age,City,State,SignupDate,Segment,Acquisition
12115,C001014,Krishna Reddy,Female,27,Surat,Gujarat,2022-02-18,Consumer,Email
12116,C008337,Sneha Sharma,Male,21,Patna,Bihar,2022-03-24,Consumer,Marketplace
12117,C011614,Tanya Das Jr,Male,18,Surat,Gujarat,2025-03-14,Consumer,Email
12118,C005233,Rahul Reddy,Female,30,Mysuru,Karnataka,2026-01-30,Consumer,Paid Search
12119,C010947,Manish Das,Female,38,Pune,Maharashtra,2025-02-25,Consumer,Paid Search

In [313]:
customers.columns

Index(['CustomerID', 'Name', 'Gender', 'Age', 'City', 'State', 'SignupDate',
       'Segment', 'Acquisition'],
      dtype='str')

In [314]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 12120 entries, 0 to 12119
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   12120 non-null  str
 1   Name         12074 non-null  str
 2   Gender       12093 non-null  str
 3   Age          12096 non-null  str
 4   City         12074 non-null  str
 5   State        12051 non-null  str
 6   SignupDate   12077 non-null  str
 7   Segment      12096 non-null  str
 8   Acquisition  12065 non-null  str
dtypes: str(9)
memory usage: 852.3 KB

In [315]:
customers.describe(include="all")

,CustomerID,Name,Gender,Age,City,State,SignupDate,Segment,Acquisition
count,12120,12074,12093,12096,12074,12051,12077,12096,12065
unique,12000,835,11,62,98,56,1772,10,13
top,C000072,Manish Das,Female,18,Pune,Maharashtra,2027-01-15,Consumer,Organic Search
freq,2,35,5835,995,547,1501,42,7343,2913

In [316]:
customers.isna().sum()

CustomerID      0
Name           46
Gender         27
Age            24
City           46
State          69
SignupDate     43
Segment        24
Acquisition    55
dtype: int64

In [317]:
customers.duplicated().sum()

np.int64(60)

In [318]:
customers["Gender"].value_counts()

Gender
Female        5835
Male          5792
Non-Binary     231
male            34
Unknown         33
M               32
FEMALE          32
MALE            29
female          28
F               28
N/B             19
Name: count, dtype: int64

In [319]:
customers["Gender"] = customers["Gender"].str.title()

In [320]:
customers["Gender"].value_counts()

Gender
Female        5895
Male          5855
Non-Binary     231
Unknown         33
M               32
F               28
N/B             19
Name: count, dtype: int64

In [321]:
customers["Gender"] = customers["Gender"].replace("M" , "Male")

In [322]:
customers["Gender"].value_counts()

Gender
Female        5895
Male          5887
Non-Binary     231
Unknown         33
F               28
N/B             19
Name: count, dtype: int64

In [323]:
customers["Gender"] = customers["Gender"].replace("F" , "Female")

In [324]:
customers["Gender"].value_counts()

Gender
Female        5923
Male          5887
Non-Binary     231
Unknown         33
N/B             19
Name: count, dtype: int64

In [325]:
customers["Gender"] = customers["Gender"].replace("N/B", "Non-Binary")

In [326]:
customers["Gender"].value_counts()

Gender
Female        5923
Male          5887
Non-Binary     250
Unknown         33
Name: count, dtype: int64

In [327]:
customers["City"] = customers["City"].str.title()

In [328]:
customers["City"].isna().sum()

np.int64(46)

In [329]:
customers["City"] = customers["City"].fillna("Unknown")

In [330]:
customers["City"].isna().sum()

np.int64(0)

In [331]:
customers["Age"].isna().sum()

np.int64(24)

In [332]:
customers["Age"] = pd.to_numeric(customers["Age"], errors="coerce")

In [333]:
customers["Age"] = customers["Age"].fillna(customers["Age"].median())

In [334]:
customers["Age"].isna().sum()

np.int64(0)

In [335]:
customers.head(1)

,CustomerID,Name,Gender,Age,City,State,SignupDate,Segment,Acquisition
0,C000001,Aditi Sharma,Male,46.0,Guwahati,Assam,2023-12-19,Consumer,Organic Search

In [336]:
customers["State"] = customers["City"].str.title()

In [337]:
customers["Gender"] = customers["Gender"].fillna("Unknown")

In [338]:
customers["Age"] = customers["Age"].astype(int)

In [339]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 12120 entries, 0 to 12119
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   12120 non-null  str
 1   Name         12074 non-null  str
 2   Gender       12120 non-null  str
 3   Age          12120 non-null  int64
 4   City         12120 non-null  str
 5   State        12120 non-null  str
 6   SignupDate   12077 non-null  str
 7   Segment      12096 non-null  str
 8   Acquisition  12065 non-null  str
dtypes: int64(1), str(8)
memory usage: 852.3 KB

In [340]:
customers["SignupDate"] = pd.to_datetime(
    customers["SignupDate"],
    format="mixed",
    errors="coerce"
)

In [341]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 12120 entries, 0 to 12119
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   12120 non-null  str
 1   Name         12074 non-null  str
 2   Gender       12120 non-null  str
 3   Age          12120 non-null  int64
 4   City         12120 non-null  str
 5   State        12120 non-null  str
 6   SignupDate   12050 non-null  datetime64[us]
 7   Segment      12096 non-null  str
 8   Acquisition  12065 non-null  str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 852.3 KB

In [342]:
customers.isna().sum()

CustomerID      0
Name           46
Gender          0
Age             0
City            0
State           0
SignupDate     70
Segment        24
Acquisition    55
dtype: int64

In [343]:
customers["Segment"] = customers["Segment"].fillna("Unknown")

In [344]:
customers["Acquisition"] = customers["Acquisition"].fillna("Unknown")

In [345]:
customers["Name"] = customers["Name"].fillna("Unknown")

In [346]:
customers.isna().sum()
#keeping missing SignupDate values as NaN because the actual signup date cannot be reliably determined

CustomerID      0
Name            0
Gender          0
Age             0
City            0
State           0
SignupDate     70
Segment         0
Acquisition     0
dtype: int64

In [347]:
customers = customers.drop_duplicates()

In [348]:
customers["CustomerID"].duplicated().sum()

np.int64(60)

In [349]:
customers[customers["CustomerID"].duplicated(keep=False)].sort_values("CustomerID")

,CustomerID,Name,Gender,Age,City,State,SignupDate,Segment,Acquisition
448,C000449,Isha Kumar,Female,28,Bhubaneswar,Bhubaneswar,2023-06-10,Consumer,Paid Search
12006,C000449,Isha Kumar Jr,Female,28,Bhubaneswar,Bhubaneswar,2023-06-10,Consumer,Paid Search
540,C000541,Nisha Yadav,Female,37,Bengaluru,Bengaluru,2022-02-16,Consumer,Paid Search
12018,C000541,Nisha Yadav Jr,Female,37,Bengaluru,Bengaluru,2022-02-16,Consumer,Paid Search
814,C000815,Vivaan Kapoor,Female,41,Nagpur,Nagpur,2025-03-02,Consumer,Social Media
...,...,...,...,...,...,...,...,...,...
11327,C011328,Ananya Kumar,Male,32,Ahmedabad,Ahmedabad,2022-08-03,HomeOffice,Social Media
12042,C011478,Varun Das Jr,Female,28,Chandigarh,Chandigarh,2022-09-23,Consumer,Social Media
11477,C011478,Varun Das,Female,28,Chandigarh,Chandigarh,2022-09-23,Consumer,Social Media
11613,C011614,Tanya Das,Male,18,Surat,Surat,2025-03-14,Consumer,Email
12117,C011614,Tanya Das Jr,Male,18,Surat,Surat,2025-03-14,Consumer,Email

In [350]:
customers["Name"] = customers["Name"].str.replace(
    r"\s+Jr\.?$", 
    "", 
    regex=True
)

In [351]:
customers = customers.drop_duplicates()

In [352]:
customers.duplicated().sum()

np.int64(0)

In [353]:
customers.info()

<class 'pandas.DataFrame'>
Index: 12030 entries, 0 to 12116
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   12030 non-null  str
 1   Name         12030 non-null  str
 2   Gender       12030 non-null  str
 3   Age          12030 non-null  int64
 4   City         12030 non-null  str
 5   State        12030 non-null  str
 6   SignupDate   11960 non-null  datetime64[us]
 7   Segment      12030 non-null  str
 8   Acquisition  12030 non-null  str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 939.8 KB

In [354]:
customers["CustomerID"].duplicated().sum()

np.int64(30)

In [355]:
customers[
    customers["CustomerID"].duplicated(keep=False)
].sort_values("CustomerID")

,CustomerID,Name,Gender,Age,City,State,SignupDate,Segment,Acquisition
814,C000815,Vivaan Kapoor,Female,41,Nagpur,Nagpur,2025-03-02,Consumer,Social Media
12084,C000815,Vivaan Kapoor,Female,41,Nagpur,Nagpur,2025-03-02,Corporate,Social Media
1502,C001503,Meera Mishra,Male,31,Jaipur,Jaipur,2022-04-10,Consumer,Social Media
12076,C001503,Meera Mishra,Male,31,Jaipur,Jaipur,2022-04-10,Corporate,Social Media
1729,C001730,Priya Malhotra,Male,29,Delhi,Delhi,2026-05-05,Home Office,Referral
12092,C001730,Priya Malhotra,Male,29,Delhi,Delhi,2026-05-05,Consumer,Referral
2077,C002078,Ishaan Bose,Female,25,Bhopal,Bhopal,2024-05-28,Consumer,Paid Search
12044,C002078,Ishaan Bose,Female,25,Bhopal,Bhopal,2024-05-28,Corporate,Paid Search
2133,C002134,Varun Malhotra,Female,18,Ahmedabad,Ahmedabad,2025-10-02,Consumer,Organic Search
12048,C002134,Varun Malhotra,Female,18,Ahmedabad,Ahmedabad,2025-10-02,Corporate,Organic Search
12036,C002852,Ananya Joshi,Male,22,Indore,Indore,2024-06-12,Corporate,Paid Search
2851,C002852,Ananya Joshi,Male,22,Indore,Indore,2024-06-12,Consumer,Paid Search
12112,C003066,Meera Gupta,Female,43,Chandigarh,Chandigarh,2022-06-14,Corporate,Email
3065,C003066,Meera Gupta,Female,43,Chandigarh,Chandigarh,2022-06-14,Consumer,Email
12004,C003245,Priya Singh,Female,34,Noida,Noida,2026-02-15,Corporate,Referral
3244,C003245,Priya Singh,Female,34,Noida,Noida,2026-02-15,Consumer,Referral
4565,C004566,Isha Chopra,Male,47,Lucknow,Lucknow,2024-08-13,Consumer,Marketplace
12032,C004566,Isha Chopra,Male,47,Lucknow,Lucknow,2024-08-13,Corporate,Marketplace
4996,C004997,Manish Das,Male,0,Jaipur,Jaipur,2023-03-12,Consumer,Organic Search
12104,C004997,Manish Das,Male,0,Jaipur,Jaipur,2023-03-12,Corporate,Organic Search
12096,C005496,Reyansh Verma,Male,40,Gurugram,Gurugram,2026-07-01,Corporate,Organic Search
5495,C005496,Reyansh Verma,Male,40,Gurugram,Gurugram,2026-07-01,Consumer,Organic Search
12000,C005534,Neha Reddy,Female,21,Chennai,Chennai,2023-02-17,Corporate,Email
5533,C005534,Neha Reddy,Female,21,Chennai,Chennai,2023-02-17,Consumer,Email
12016,C005788,Karan Chopra,Unknown,35,Lucknow,Lucknow,2022-03-18,Consumer,Organic Search
5787,C005788,Karan Chopra,Unknown,35,Lucknow,Lucknow,2022-03-18,Corporate,Organic Search
12024,C005904,Krishna Singh,Male,53,Gurugram,Gurugram,2023-05-04,Consumer,Paid Search
5903,C005904,Krishna Singh,Male,53,Gurugram,Gurugram,2023-05-04,Corporate,Paid Search
6282,C006283,Nikhil Singh,Male,45,Nagpur,Nagpur,2026-01-04,Consumer,Social Media
12008,C006283,Nikhil Singh,Male,45,Nagpur,Nagpur,2026-01-04,Corporate,Social Media
12068,C006378,Manish Chopra,Male,32,Hyderabad,Hyderabad,2024-05-16,Corporate,Marketplace
6377,C006378,Manish Chopra,Male,32,Hyderabad,Hyderabad,2024-05-16,Consumer,Marketplace
6499,C006500,Sanya Nair,Male,21,Chandigarh,Chandigarh,2026-05-01,Corporate,Affiliate
12040,C006500,Sanya Nair,Male,21,Chandigarh,Chandigarh,2026-05-01,Consumer,Affiliate
7196,C007197,Krishna Yadav,Male,42,Hyderabad,Hyderabad,2024-01-19,Consumer,Social Media
12060,C007197,Krishna Yadav,Male,42,Hyderabad,Hyderabad,2024-01-19,Corporate,Social Media
12064,C007294,Arjun Gupta,Female,20,Hyderabad,Hyderabad,2027-01-15,Consumer,Paid Search
7293,C007294,Arjun Gupta,Female,20,Hyderabad,Hyderabad,2027-01-15,Corporate,Paid Search
12020,C007920,Aditya Reddy,Male,26,Bengaluru,Bengaluru,2023-08-12,Consumer,Paid Search
7919,C007920,Aditya Reddy,Male,26,Bengaluru,Bengaluru,2023-08-12,Corporate,Paid Search
12116,C008337,Sneha Sharma,Male,21,Patna,Patna,2022-03-24,Consumer,Marketplace
8336,C008337,Sneha Sharma,Male,21,Patna,Patna,2022-03-24,Corporate,Marketplace
12100,C008743,Varun Joshi,Male,36,Guwahati,Guwahati,2023-01-14,Corporate,Email
8742,C008743,Varun Joshi,Male,36,Guwahati,Guwahati,2023-01-14,Consumer,Email
12080,C009027,Aditya Bose,Female,43,Bhubaneswar,Bhubaneswar,2024-02-29,Corporate,Affiliate
9026,C009027,Aditya Bose,Female,43,Bhubaneswar,Bhubaneswar,2024-02-29,Consumer,Affiliate
9086,C009087,Riya Joshi,Female,26,Bengaluru,Bengaluru,2024-11-01,Consumer,Social Media
12012,C009087,Riya Joshi,Female,26,Bengaluru,Bengaluru,2024-11-01,Corporate,Social Media
9512,C009513,Sanya Kumar,Male,35,Jaipur,Jaipur,2023-07-31,Corporate,Organic Search
12052,C009513,Sanya Kumar,Male,35,Jaipur,Jaipur,2023-07-31,Consumer,Organic Search
12088,C009602,Sneha Bose,Female,30,Delhi,Delhi,2026-06-03,Consumer,Social Media
9601,C009602,Sneha Bose,Female,30,Delhi,Delhi,2026-06-03,Small Business,Social Media
12072,C010004,Neha Kumar,Male,23,Chandigarh,Chandigarh,2024-11-25,Corporate,Organic Search
10003,C010004,Neha Kumar,Male,23,Chandigarh,Chandigarh,2024-11-25,Consumer,Organic Search
12028,C010109,Varun Shah,Female,39,Noida,Noida,2026-05-09,Consumer,Referral
10108,C010109,Varun Shah,Female,39,Noida,Noida,2026-05-09,Corporate,Referral
10697,C010698,Kavya Rao,Female,18,Kochi,Kochi,2023-09-08,Corporate,Social Media
12108,C010698,Kavya Rao,Female,18,Kochi,Kochi,2023-09-08,Consumer,Social Media
12056,C011035,Aditi Das,Female,31,Indore,Indore,2024-09-25,Consumer,Paid Search
11034,C011035,Aditi Das,Female,31,Indore,Indore,2024-09-25,Corporate,Paid Search

In [356]:
customers = customers.drop_duplicates(
    subset="CustomerID",
    keep="first"
)

In [357]:
customers["CustomerID"].duplicated().sum()

np.int64(0)

In [358]:
customers["SignupDate"].max()

Timestamp('2027-01-15 00:00:00')

In [359]:
(customers["SignupDate"] > pd.Timestamp("2026-08-14")).sum()

np.int64(42)

In [360]:
customers.loc[customers["SignupDate"] > "2026-08-14", "SignupDate"] = pd.NaT
#replaced invalid future signup dates with NaT because signup dates cannot be beyond the dataset's reporting date (14-Aug-2026)

In [361]:
customers["SignupDate"].max()

Timestamp('2026-07-31 00:00:00')

In [362]:
customers.isna().sum()

CustomerID       0
Name             0
Gender           0
Age              0
City             0
State            0
SignupDate     112
Segment          0
Acquisition      0
dtype: int64

In [363]:
customers["City"]= customers["City"].str.title()

In [364]:
customers["State"]= customers["State"].str.title()

In [365]:
customers["Segment"]= customers["Segment"].str.title()

In [366]:
customers["Segment"].value_counts()

Segment
Consumer          7322
Corporate         2048
Home Office       1553
Small Business     944
Corp                29
Consumr             28
Homeoffice          27
Small Biz           26
Unknown             23
Name: count, dtype: int64

In [367]:
customers["Segment"] = customers["Segment"].replace("Corp" , "Corporate")

In [368]:
customers["Segment"] = customers["Segment"].replace("CONSUMER" , "Consumer")

In [369]:
customers["Segment"] = customers["Segment"].replace("consumer" , "Consumer")

In [370]:
customers["Segment"] = customers["Segment"].replace("Consumr" , "Consumer")

In [371]:
customers["Segment"] = customers["Segment"].replace("HomeOffice" , "Home Office")

In [372]:
customers["Segment"] = customers["Segment"].replace("Small Biz" , "Small Business")

In [373]:
customers["Segment"] = customers["Segment"].replace("Homeoffice" , "Home Office")

In [374]:
customers["Segment"].value_counts()

Segment
Consumer          7350
Corporate         2077
Home Office       1580
Small Business     970
Unknown             23
Name: count, dtype: int64

In [375]:
customers.info()

<class 'pandas.DataFrame'>
Index: 12000 entries, 0 to 11999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   12000 non-null  str
 1   Name         12000 non-null  str
 2   Gender       12000 non-null  str
 3   Age          12000 non-null  int64
 4   City         12000 non-null  str
 5   State        12000 non-null  str
 6   SignupDate   11888 non-null  datetime64[us]
 7   Segment      12000 non-null  str
 8   Acquisition  12000 non-null  str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 937.5 KB

In [376]:
customers["Acquisition"].value_counts()

Acquisition
Organic Search    2880
Social Media      2345
Paid Search       2251
Referral          1318
Marketplace       1238
Email             1151
Affiliate          627
Unknown             55
market place        34
PAID SEARCH         26
organic search      25
E-mail              20
social              18
Referal             12
Name: count, dtype: int64

In [377]:
customers["Acquisition"] = customers["Acquisition"].replace("market place","Marketplace")

In [378]:
customers["Acquisition"] = customers["Acquisition"].replace("Referal","Referral")

In [379]:
customers["Acquisition"] = customers["Acquisition"].replace("Referal","Referral")

In [380]:
customers["Acquisition"] = customers["Acquisition"].replace("social","Social Media")

In [381]:
customers["Acquisition"] = customers["Acquisition"].replace("E-mail","Email")

In [382]:
customers["Acquisition"] = customers["Acquisition"].replace("organic search","Organic Search")

In [383]:
customers["Acquisition"] = customers["Acquisition"].replace("PAID SEARCH","Paid Search")

In [384]:
customers["Acquisition"].value_counts()

Acquisition
Organic Search    2905
Social Media      2363
Paid Search       2277
Referral          1330
Marketplace       1272
Email             1171
Affiliate          627
Unknown             55
Name: count, dtype: int64

In [385]:
customers.info()

<class 'pandas.DataFrame'>
Index: 12000 entries, 0 to 11999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   12000 non-null  str
 1   Name         12000 non-null  str
 2   Gender       12000 non-null  str
 3   Age          12000 non-null  int64
 4   City         12000 non-null  str
 5   State        12000 non-null  str
 6   SignupDate   11888 non-null  datetime64[us]
 7   Segment      12000 non-null  str
 8   Acquisition  12000 non-null  str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 937.5 KB

In [386]:
customers["State"].str.startswith(" ").sum()

np.int64(42)

In [387]:
customers["State"]= customers["State"].str.strip()

In [388]:
customers["State"].str.startswith(" ").sum()

np.int64(0)

In [389]:
customers["State"].str.endswith(" ").sum()

np.int64(0)

In [390]:
customers["City"].str.startswith(" ").sum()

np.int64(42)

In [391]:
customers["City"]= customers["City"].str.strip()

In [392]:
customers["City"].str.startswith(" ").sum()

np.int64(0)

In [393]:
customers["City"].str.endswith(" ").sum()

np.int64(0)

In [394]:
customers["Segment"].str.startswith(" ").sum()

np.int64(0)

In [395]:
customers["Segment"].str.endswith(" ").sum()

np.int64(0)

In [396]:
customers["Acquisition"].str.startswith(" ").sum()

np.int64(0)

In [397]:
customers["Acquisition"].str.endswith(" ").sum()

np.int64(0)

In [398]:
customers["Name"].str.startswith(" ").sum()

np.int64(57)

In [399]:
customers["Name"] = customers["Name"].str.strip()

In [400]:
customers["Name"].str.startswith(" ").sum()

np.int64(0)

In [401]:
customers["Name"].str.endswith(" ").sum()

np.int64(0)

In [402]:
customers["Gender"].str.endswith(" ").sum()

np.int64(0)

In [403]:
customers.duplicated().sum()

np.int64(0)

In [404]:
age_median = customers["Age"].median()

In [405]:
age_median

np.float64(34.0)

In [406]:
invalid_age = (
    (customers["Age"] < 18) |
    (customers["Age"] > 100)
)
invalid_age.value_counts()

Age
False    11896
True       104
Name: count, dtype: int64

In [407]:
customers.loc[invalid_age, "Age"] = age_median

In [408]:
customers[customers["Age"] < 18]

Empty DataFrame
Columns: [CustomerID, Name, Gender, Age, City, State, SignupDate, Segment, Acquisition]
Index: []

In [409]:
customers[customers["Age"] > 100]

Empty DataFrame
Columns: [CustomerID, Name, Gender, Age, City, State, SignupDate, Segment, Acquisition]
Index: []

In [410]:
customers_clean_data = customers.copy()

In [411]:
customers_clean_data.to_csv("customers_clean_data.csv",index=False)

In [412]:
orders.head()

,OrderID,CustomerID,OrderDate,PaymentMethod,OrderStatus,DeliveryDate,ShippingCost
0,O0000001,C005491,2023-02-27,UPI,Cancelled,NaN,0.00
1,O0000002,C009711,2025-09-23,Credit Card,Delivered,2025-10-01,70.11
2,O0000003,C006489,2025-02-05,Credit Card,Delivered,2025-02-06,0.00
3,O0000004,C008378,2024-05-25,Credit Card,Delivered,2024-05-31,94.32
4,O0000005,C000540,2023-10-16,Wallet,Delivered,2023-10-23,0.00

In [413]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 32320 entries, 0 to 32319
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        32320 non-null  str
 1   CustomerID     32290 non-null  str
 2   OrderDate      32284 non-null  str
 3   PaymentMethod  32297 non-null  str
 4   OrderStatus    32293 non-null  str
 5   DeliveryDate   27758 non-null  str
 6   ShippingCost   32270 non-null  str
dtypes: str(7)
memory usage: 1.7 MB

In [414]:
orders["OrderDate"] = pd.to_datetime(
    orders["OrderDate"],
    format="mixed",
    errors="coerce"
)

In [415]:
orders["DeliveryDate"] = pd.to_datetime(
    orders["DeliveryDate"],
    format="mixed",
    errors="coerce"
)

In [416]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 32320 entries, 0 to 32319
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        32320 non-null  str
 1   CustomerID     32290 non-null  str
 2   OrderDate      32204 non-null  datetime64[us]
 3   PaymentMethod  32297 non-null  str
 4   OrderStatus    32293 non-null  str
 5   DeliveryDate   27719 non-null  datetime64[us]
 6   ShippingCost   32270 non-null  str
dtypes: datetime64[us](2), str(5)
memory usage: 1.7 MB

In [417]:
orders.duplicated().sum()

np.int64(171)

In [418]:
orders = orders.drop_duplicates()

In [419]:
orders.duplicated().sum()

np.int64(0)

In [420]:
orders["OrderID"].duplicated().sum()

np.int64(149)

In [421]:
orders[
    orders["OrderID"].duplicated(keep=False)
].sort_values("OrderID")

,OrderID,CustomerID,OrderDate,PaymentMethod,OrderStatus,DeliveryDate,ShippingCost
7,O0000008,C002594,2026-05-15,Credit Card,Cancelled,NaT,158.05
32099,O0000008,C002594,2026-05-15,UPI,Cancelled,NaT,158.05
106,O0000107,C004307,2024-06-15,Net Banking,Delivered,2024-06-23,1.68
32105,O0000107,C004307,2024-06-15,UPI,Delivered,2024-06-23,0
506,O0000507,C002141,2024-12-15,Wallet,Delivered,2024-12-22,120.00
...,...,...,...,...,...,...,...
32312,O0031716,C003156,2023-12-09,UPI,Cancelled,NaT,101.39
31755,O0031756,C002465,2023-04-26,UPI,Delivered,2023-04-29,86.59
32168,O0031756,C002465,2023-04-26,Cash on Delivery,Delivered,2023-04-29,86.59
32282,O0031910,C002336,2026-03-05,UPI,Delivered,2026-03-12,50.05
31909,O0031910,C002336,2026-03-05,Wallet,Delivered,2026-03-12,50.05

In [422]:
orders = orders.drop_duplicates(
    subset="OrderID",
    keep="first"
)

In [423]:
orders["OrderID"].duplicated().sum()

np.int64(0)

In [424]:
orders.isnull().sum()

OrderID             0
CustomerID         30
OrderDate         115
PaymentMethod      23
OrderStatus        27
DeliveryDate     4545
ShippingCost       50
dtype: int64

In [425]:
orders = orders.dropna(subset=["CustomerID"])

In [426]:
orders = orders.dropna(subset=["OrderDate"])

In [427]:
orders

,OrderID,CustomerID,OrderDate,PaymentMethod,OrderStatus,DeliveryDate,ShippingCost
0,O0000001,C005491,2023-02-27,UPI,Cancelled,NaT,0.00
1,O0000002,C009711,2025-09-23,Credit Card,Delivered,2025-10-01,70.11
2,O0000003,C006489,2025-02-05,Credit Card,Delivered,2025-02-06,0.00
3,O0000004,C008378,2024-05-25,Credit Card,Delivered,2024-05-31,94.32
4,O0000005,C000540,2023-10-16,Wallet,Delivered,2023-10-23,0.00
...,...,...,...,...,...,...,...
31995,O0031996,C006164,2024-05-03,UPI,Delivered,2024-05-08,104.39
31996,O0031997,C007448,2023-06-23,Debit Card,Delivered,2023-06-29,104.76
31997,O0031998,C000465,2024-12-04,Credit Card,Delivered,2024-12-11,195.16
31998,O0031999,C002230,2024-11-02,UPI,Delivered,2024-11-09,118.00
31999,O0032000,C003082,2024-09-29,UPI,Delivered,2024-10-03,52.43

In [428]:
orders["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
UPI                 9778
Credit Card         6625
Cash on Delivery    5431
Debit Card          4101
Net Banking         3186
Wallet              2515
wallet                28
CreditCard            27
upi                   25
Cash                  25
debit card            24
COD                   24
Crypto                23
NaN                   23
NetBanking            20
Name: count, dtype: int64

In [429]:
orders["PaymentMethod"] = orders["PaymentMethod"].str.title()

In [430]:
orders["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Upi                 9803
Credit Card         6625
Cash On Delivery    5431
Debit Card          4125
Net Banking         3186
Wallet              2515
Wallet                28
Creditcard            27
Cash                  25
Cod                   24
Crypto                23
NaN                   23
Netbanking            20
Name: count, dtype: int64

In [431]:
orders["PaymentMethod"] = orders["PaymentMethod"].replace("Creditcard", "Credit Card")

In [432]:
orders["PaymentMethod"] = orders["PaymentMethod"].replace("Cash", "Cash On Delivery")

In [433]:
orders["PaymentMethod"] = orders["PaymentMethod"].replace("Cod", "Cash On Delivery")

In [434]:
orders["PaymentMethod"] = orders["PaymentMethod"].replace("Netbanking", "Net Banking")

In [435]:
orders["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Upi                 9803
Credit Card         6652
Cash On Delivery    5480
Debit Card          4125
Net Banking         3206
Wallet              2515
Wallet                28
Crypto                23
NaN                   23
Name: count, dtype: int64

In [436]:
orders["PaymentMethod"] = orders["PaymentMethod"].fillna("Unknown")

In [437]:
orders["PaymentMethod"] = orders["PaymentMethod"].str.strip()

In [438]:
orders["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Upi                 9803
Credit Card         6652
Cash On Delivery    5480
Debit Card          4125
Net Banking         3206
Wallet              2543
Crypto                23
Unknown               23
Name: count, dtype: int64

In [439]:
orders["PaymentMethod"] = orders["PaymentMethod"].str.title()

In [440]:
orders["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Upi                 9803
Credit Card         6652
Cash On Delivery    5480
Debit Card          4125
Net Banking         3206
Wallet              2543
Crypto                23
Unknown               23
Name: count, dtype: int64

In [441]:
orders["OrderStatus"].value_counts(dropna=False)

OrderStatus
Delivered      25296
Cancelled       2516
Returned        1631
Shipped         1559
Processing       633
delivered         34
Return            32
In Transit        29
NaN               27
Canceled          27
processing        27
Unknown           22
DELIVERED         22
Name: count, dtype: int64

In [442]:
orders["OrderStatus"] = orders["OrderStatus"].str.title()

In [443]:
orders["OrderStatus"].value_counts(dropna=False)

OrderStatus
Delivered      25352
Cancelled       2516
Returned        1631
Shipped         1559
Processing       633
Return            32
In Transit        29
NaN               27
Canceled          27
Processing        27
Unknown           22
Name: count, dtype: int64

In [444]:
orders["OrderStatus"] = orders["OrderStatus"].replace("Return","Returned")

In [445]:
orders["OrderStatus"] = orders["OrderStatus"].replace("Canceled","Cancelled")

In [446]:
orders["OrderStatus"] = orders["OrderStatus"].str.strip()

In [447]:
orders["OrderStatus"].value_counts(dropna=False)

OrderStatus
Delivered     25352
Cancelled      2543
Returned       1663
Shipped        1559
Processing      660
In Transit       29
NaN              27
Unknown          22
Name: count, dtype: int64

In [448]:
orders["OrderStatus"] = orders["OrderStatus"].fillna("Unknown")

In [449]:
orders["OrderStatus"].value_counts(dropna=False)

OrderStatus
Delivered     25352
Cancelled      2543
Returned       1663
Shipped        1559
Processing      660
Unknown          49
In Transit       29
Name: count, dtype: int64

In [450]:
(orders["DeliveryDate"] > "2026-08-14").sum()

np.int64(37)

In [451]:
orders.loc[orders["DeliveryDate"] > "2026-08-14", "DeliveryDate"] = pd.NaT

In [452]:
(orders["DeliveryDate"] > "2026-08-14").sum()

np.int64(0)

In [453]:
orders.isnull().sum()

OrderID             0
CustomerID          0
OrderDate           0
PaymentMethod       0
OrderStatus         0
DeliveryDate     4556
ShippingCost       49
dtype: int64

In [454]:
orders[orders["DeliveryDate"].isna()]["OrderStatus"].value_counts()

OrderStatus
Cancelled     2517
Shipped       1247
Processing     637
Delivered      133
Returned        14
Unknown          6
In Transit       2
Name: count, dtype: int64

In [455]:
orders.loc[
    orders["DeliveryDate"].isna() &
    (orders["OrderStatus"] == "Delivered"),
    "DeliveryDate"
] = pd.NaT

In [456]:
orders.isnull().sum()

OrderID             0
CustomerID          0
OrderDate           0
PaymentMethod       0
OrderStatus         0
DeliveryDate     4556
ShippingCost       49
dtype: int64

In [457]:
orders.info()

<class 'pandas.DataFrame'>
Index: 31855 entries, 0 to 31999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        31855 non-null  str
 1   CustomerID     31855 non-null  str
 2   OrderDate      31855 non-null  datetime64[us]
 3   PaymentMethod  31855 non-null  str
 4   OrderStatus    31855 non-null  str
 5   DeliveryDate   27299 non-null  datetime64[us]
 6   ShippingCost   31806 non-null  str
dtypes: datetime64[us](2), str(5)
memory usage: 1.9 MB

In [458]:
orders["ShippingCost"] = pd.to_numeric(
    orders["ShippingCost"],
    errors="coerce"
)

In [459]:
orders["ShippingCost"] = orders["ShippingCost"].fillna(
    orders["ShippingCost"].median()
)

In [460]:
orders.info()

<class 'pandas.DataFrame'>
Index: 31855 entries, 0 to 31999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        31855 non-null  str
 1   CustomerID     31855 non-null  str
 2   OrderDate      31855 non-null  datetime64[us]
 3   PaymentMethod  31855 non-null  str
 4   OrderStatus    31855 non-null  str
 5   DeliveryDate   27299 non-null  datetime64[us]
 6   ShippingCost   31855 non-null  float64
dtypes: datetime64[us](2), float64(1), str(4)
memory usage: 1.9 MB

In [461]:
(orders["OrderDate"] > "2026-08-31").sum()

np.int64(48)

In [462]:
orders.loc[
    orders["OrderDate"] > "2026-08-14",
    "OrderDate"
] = pd.NaT

In [463]:
(orders["OrderDate"] > "2026-08-31").sum()

np.int64(0)

In [464]:
orders.loc[orders["ShippingCost"] < 0, "ShippingCost"] = np.nan

In [465]:
orders["ShippingCost"] = orders["ShippingCost"].fillna(
    orders["ShippingCost"].median()
)

In [466]:
(orders["ShippingCost"] < 0).sum()

np.int64(0)

In [467]:
orders["OrderID"].duplicated().sum()

np.int64(0)

In [468]:
orders_clean_data = orders.copy()

In [469]:
orders_clean_data.to_csv("orders_clean_data.csv",index=False)

In [470]:
sales.head()

,OrderItemID,OrderID,ProductID,Quantity,UnitPrice,Discount,GrossSales,DiscountAmount,NetSales,Tax,TotalCost,Profit
0,OI00000001,O0029046,P00422,4,4318.82,0.00,17275.28,0.00,17275.28,2073.03,9079.08,8196.20
1,OI00000002,O0017104,P01523,1,12291.71,0.05,12291.71,614.59,11677.12,2101.88,8751.62,2925.50
2,OI00000003,O0000452,P01327,5,3653.38,0.40,18266.90,7306.76,10960.14,1972.83,10480.25,479.89
3,OI00000004,O0010615,P01023,1,11547.81,0.00,11547.81,0.00,11547.81,2078.61,6372.36,5175.45
4,OI00000005,O0010012,P01086,1,16442.06,0.20,16442.06,3288.41,13153.65,2367.66,9885.70,3267.95

In [471]:
sales.isna().sum()

OrderItemID         0
OrderID           124
ProductID         137
Quantity          100
UnitPrice         238
Discount           98
GrossSales        224
DiscountAmount    240
NetSales          227
Tax               166
TotalCost         226
Profit            418
dtype: int64

In [472]:
sales.duplicated().sum()

np.int64(375)

In [473]:
sales=sales.drop_duplicates()

In [474]:
sales["OrderItemID"].duplicated().sum()

np.int64(125)

In [475]:
sales[
    sales["OrderItemID"].duplicated(keep=False)
].sort_values("OrderItemID")

,OrderItemID,OrderID,ProductID,Quantity,UnitPrice,Discount,GrossSales,DiscountAmount,NetSales,Tax,TotalCost,Profit
384,OI00000385,O0022323,P00928,1,27675.92,0.00,27675.92,0.00,27675.92,4981.67,16177.48,11498.44
99932,OI00000385,O0022323,P00928,2,27675.92,0.00,27675.92,0.00,27675.92,4981.67,16177.48,11498.44
99556,OI00002170,O0010112,P00010,2,11085.62,0.20,11085.62,2217.12,8868.50,1064.22,8476.73,391.77
2169,OI00002170,O0010112,P00010,1,11085.62,0.20,11085.62,2217.12,8868.50,1064.22,8476.73,391.77
2225,OI00002226,O0007303,P00583,2,585.96,0.05,1171.92,58.60,1113.32,200.40,651.28,462.04
...,...,...,...,...,...,...,...,...,...,...,...,...
98056,OI00098057,O0013847,P00267,1,5747.16,0.10,5747.16,574.72,5172.44,931.04,3025.26,2147.18
98581,OI00098582,O0027839,P01547,1,806.57,0.00,806.57,0.00,806.57,145.18,618.39,188.18
99500,OI00098582,O0027839,P01547,2,806.57,0.00,806.57,0.00,806.57,145.18,618.39,188.18
99724,OI00098776,O0012942,P00983,2,5249.72,0.05,20998.88,1049.94,19948.94,997.45,11326.52,8622.42
98775,OI00098776,O0012942,P00983,4,5249.72,0.05,20998.88,1049.94,19948.94,997.45,11326.52,8622.42

In [476]:
sales = sales.drop_duplicates("OrderItemID")

In [477]:
sales["Quantity"].dtype

In [478]:
sales["Quantity"] = pd.to_numeric(
    sales["Quantity"],
    errors="coerce"
)

In [479]:
sales["Quantity"] = sales["Quantity"].astype("Int64")

In [480]:
sales["Quantity"] = sales["Quantity"].astype("Int64")

In [481]:
sales["Quantity"].isna().sum()

np.int64(176)

In [482]:
sales.dtypes

OrderItemID         str
OrderID             str
ProductID           str
Quantity          Int64
UnitPrice           str
Discount            str
GrossSales          str
DiscountAmount      str
NetSales            str
Tax                 str
TotalCost           str
Profit              str
dtype: object

In [483]:
numeric_cols = [
    "UnitPrice",
    "Discount",
    "GrossSales",
    "DiscountAmount",
    "NetSales",
    "Tax",
    "TotalCost",
    "Profit"
]

for col in numeric_cols:
    sales[col] = pd.to_numeric(
        sales[col],
        errors="coerce"
    )

In [484]:
sales = sales.dropna(subset=["Quantity"])

In [485]:
sales[sales["Quantity"] == 0 ]

,OrderItemID,OrderID,ProductID,Quantity,UnitPrice,Discount,GrossSales,DiscountAmount,NetSales,Tax,TotalCost,Profit
682,OI00000683,O0000585,P00683,0,8331.25,0.25,33325.00,8331.25,24993.75,4498.88,18890.20,6103.55
1348,OI00001349,O0030154,P01235,0,2007.71,0.20,2007.71,401.54,1606.17,80.31,1559.48,46.69
4350,OI00004351,O0002255,P01162,0,850.35,0.15,2551.05,382.66,2168.39,390.31,1155.93,1012.46
5199,OI00005200,O0031914,P01843,0,1321.52,0.00,1321.52,0.00,1321.52,237.87,907.74,413.78
6461,OI00006462,O0002077,P00537,0,1660.88,0.00,1660.88,0.00,1660.88,298.96,854.94,805.94
...,...,...,...,...,...,...,...,...,...,...,...,...
96004,OI00096005,O0031455,P01932,0,824.32,0.00,1648.64,0.00,1648.64,82.43,1280.72,367.92
97710,OI00097711,O0005957,P01519,0,1506.21,0.25,3012.42,753.11,2259.31,406.68,1507.18,752.13
97734,OI00097735,O0024819,P00681,0,3066.16,0.20,3066.16,613.23,2452.93,441.53,1869.66,583.27
98104,OI00098105,O0025361,P00447,0,3951.38,0.20,3951.38,790.28,3161.10,569.00,2488.62,672.48
99148,OI00099149,O0009389,P01682,0,25861.98,0.30,25861.98,7758.59,18103.39,3258.61,17327.81,775.58

In [486]:
sales = sales[sales["Quantity"] > 0]

In [487]:
sales[sales["UnitPrice"] <= 0]

,OrderItemID,OrderID,ProductID,Quantity,UnitPrice,Discount,GrossSales,DiscountAmount,NetSales,Tax,TotalCost,Profit
59,OI00000060,O0028270,P01065,3,-999.0,0.05,11397.78,569.89,10827.89,541.39,6645.45,4182.44
435,OI00000436,O0030628,P00722,2,0.0,0.30,2282.84,684.85,1597.99,191.76,1475.10,122.89
815,OI00000816,O0000313,P00437,4,-999.0,0.10,7568.00,756.80,6811.20,340.56,5410.80,1400.40
1921,OI00001922,O0026989,P01861,3,-999.0,0.20,12180.84,2436.17,9744.67,1169.36,8322.75,1421.92
2138,OI00002139,O0026773,P01243,2,-999.0,0.00,3740.66,0.00,3740.66,673.32,1779.34,1961.32
...,...,...,...,...,...,...,...,...,...,...,...,...
94342,OI00094343,O0000151,P00741,4,0.0,0.10,1761.92,176.19,1585.73,285.43,877.56,708.17
94886,OI00094887,O0002032,P00422,2,-999.0,0.20,8537.86,1707.57,6830.29,819.63,4539.54,2290.75
96712,OI00096713,O0006041,P01903,2,0.0,0.05,16759.78,837.99,15921.79,796.09,8315.98,7605.81
97991,OI00097992,O0028572,P01610,2,0.0,0.00,3204.28,0.00,3204.28,576.77,2019.08,1185.20
98893,OI00098894,O0022956,P00469,3,-999.0,0.00,20243.04,0.00,20243.04,1012.15,12456.36,7786.68

In [488]:
sales["UnitPrice"].isna().sum()

np.int64(522)

In [489]:
sales[sales["Discount"] < 0]

,OrderItemID,OrderID,ProductID,Quantity,UnitPrice,Discount,GrossSales,DiscountAmount,NetSales,Tax,TotalCost,Profit
91,OI00000092,O0000340,P00821,2,778.11,-0.1,1556.22,233.43,1322.79,238.10,1231.26,91.53
2108,OI00002109,O0014002,P00693,2,2039.64,-0.1,4079.28,0.00,4079.28,734.27,2108.36,1970.92
2637,OI00002638,O0009839,P01091,1,800.48,-0.1,800.48,0.00,800.48,144.09,438.84,361.64
2790,OI00002791,O0009375,P00350,3,847.32,-0.1,2541.96,508.39,2033.57,244.03,1517.58,515.99
3110,OI00003111,O0019768,P00119,2,553.91,-0.1,1107.82,0.00,1107.82,55.39,783.30,324.52
...,...,...,...,...,...,...,...,...,...,...,...,...
97637,OI00097638,O0005513,P00059,1,2731.41,-0.1,2731.41,136.57,2594.84,129.74,1490.29,1104.55
98390,OI00098391,O0000068,P01156,1,2710.42,-0.1,2710.42,0.00,2710.42,325.25,1440.75,1269.67
98536,OI00098537,O0008228,P00460,1,1733.01,-0.1,1733.01,433.25,1299.76,64.99,948.04,351.72
99406,OI00099407,O0002619,P01880,2,1313.12,-0.1,2626.24,131.31,2494.93,449.09,1284.14,1210.79
99454,OI00099455,O0017182,P01477,2,2057.49,-0.1,4114.98,205.75,3909.23,703.66,3547.36,361.87

In [490]:
sales["Discount"].isna().sum()

np.int64(403)

In [491]:
sales

,OrderItemID,OrderID,ProductID,Quantity,UnitPrice,Discount,GrossSales,DiscountAmount,NetSales,Tax,TotalCost,Profit
0,OI00000001,O0029046,P00422,4,4318.82,0.00,17275.28,0.00,17275.28,2073.03,9079.08,8196.20
1,OI00000002,O0017104,P01523,1,12291.71,0.05,12291.71,614.59,11677.12,2101.88,8751.62,2925.50
2,OI00000003,O0000452,P01327,5,3653.38,0.40,18266.90,7306.76,10960.14,1972.83,10480.25,479.89
3,OI00000004,O0010615,P01023,1,11547.81,0.00,11547.81,0.00,11547.81,2078.61,6372.36,5175.45
4,OI00000005,O0010012,P01086,1,16442.06,0.20,16442.06,3288.41,13153.65,2367.66,9885.70,3267.95
...,...,...,...,...,...,...,...,...,...,...,...,...
99495,OI00099496,O0013372,P00709,4,10688.56,0.00,42754.24,0.00,42754.24,7695.76,32508.60,10245.64
99496,OI00099497,O0022603,P01982,3,7031.25,0.05,21093.75,1054.69,20039.06,1001.95,10244.76,9794.30
99497,OI00099498,O0003190,P01143,1,4070.18,0.00,4070.18,0.00,4070.18,732.63,2118.08,1952.10
99498,OI00099499,O0024514,P00766,1,13456.98,0.00,13456.98,0.00,13456.98,1614.84,10205.93,3251.05
99499,OI00099500,O0013234,P01945,3,951.61,0.10,2854.83,285.48,2569.35,128.47,1976.07,593.28

In [492]:
sales["GrossSales"].isna().sum()

np.int64(450)

In [493]:
sales["GrossSales"] = sales["GrossSales"].fillna(
    sales["Quantity"] * sales["UnitPrice"]
)

In [494]:
sales["GrossSales"].isna().sum()

np.int64(2)

In [495]:
sales["UnitPrice"].isna().sum()

np.int64(522)

In [496]:
check = np.isclose(
    sales["GrossSales"],
    sales["Quantity"] * sales["UnitPrice"],
    atol=0.01
)

np.unique(check, return_counts=True)

(array([False,  True]), array([ 1264, 97773]))

In [497]:
sales["GrossSales"] = sales["Quantity"] * sales["UnitPrice"]

In [498]:
check = np.isclose(
    sales["GrossSales"],
    sales["Quantity"] * sales["UnitPrice"],
    atol=0.01
)

np.unique(check, return_counts=True)

(array([False,  True]), array([  522, 98515]))

In [499]:
sales["DiscountAmount"].isna().sum()

np.int64(410)

In [500]:
(sales["DiscountAmount"] == 0).sum()

np.int64(29526)

In [501]:
(sales["DiscountAmount"] < 0).sum()

np.int64(37)

In [502]:
sales[sales["DiscountAmount"] < 0][
    ["Quantity", "UnitPrice", "GrossSales", "DiscountAmount","NetSales"]
].head(20)

       Quantity  UnitPrice  GrossSales  DiscountAmount  NetSales
13495         1   17634.63    17634.63          -37.50  17634.63
15622         3    8389.82    25169.46          -37.50  25169.46
24736         1     265.88      265.88          -37.50    265.88
24755         1    1507.17     1507.17          -37.50   1507.17
26331         1    1383.15     1383.15          -37.50   1383.15
28936         2    2676.08     5352.16          -37.50   5352.16
29177         2   16283.69    32567.38          -37.50  32567.38
30680       100    1199.40    119940.0          -37.50   2398.80
32042         4     645.10      2580.4          -37.50   2580.40
34139         4    3768.66    15074.64          -37.50  15074.64
34369         1    2885.13     2885.13          -37.50   2885.13
34895         4    1247.68     4990.72          -37.50   4990.72
34909         4    7343.84    29375.36          -37.50  29375.36
39721         2    1178.76     2357.52          -37.50   2357.52
41594         1     613.24      613.24          -37.50    613.24
41767         2   28124.28    56248.56          -37.50  56248.56
44219         1     250.40       250.4          -12.46    225.36
46431         3   12113.14    36339.42          -37.50  36339.42
50331         2    4090.00      8180.0          -37.50   8180.00
50432         1    4716.01     4716.01          -37.50   4716.01

In [503]:
sales["ExpectedDiscountAmount"] = (
    sales["GrossSales"] * sales["Discount"]
)

In [504]:
check = np.isclose(
    sales["DiscountAmount"],
    sales["ExpectedDiscountAmount"],
    atol=0.01
)

np.unique(check, return_counts=True)

(array([False,  True]), array([ 2352, 96685]))

In [505]:
sales["Discount"].value_counts().sort_index()

Discount
-0.10        98
 0.00     29422
 0.05      9846
 0.10     17678
 0.15     11656
 0.20     12854
 0.25      6824
 0.30      6986
 0.40      2972
 1.25       111
 10.00       97
 15.00       90
Name: count, dtype: int64

In [506]:
sales[sales["Discount"] > 0.40][
    ["GrossSales", "Discount", "DiscountAmount", "NetSales"]
].head(20)

      GrossSales  Discount  DiscountAmount  NetSales
668       1680.0      1.25            0.00   1680.00
691      3042.55      1.25            0.00   3042.55
731      3081.86      1.25            0.00   3081.86
965      8788.88      1.25            0.00   8788.88
1140     1313.38      1.25          197.01   1116.37
1400     4150.22     15.00          830.04   3320.18
2042     5434.73     10.00         2173.89   3260.84
2063    45505.56      1.25         6825.83  38679.73
2137    23497.95      1.25         2349.80  21148.15
2323      629.34      1.25           94.40    534.94
2336      3510.7      1.25          702.14   2808.56
2476     3805.08     10.00          190.25   3614.83
3345     7478.25     15.00         1495.65   5982.60
3465    14361.82      1.25         2872.36  11489.46
4549      1930.9      1.25           96.55   1834.35
5613      678.22     10.00          271.29    406.93
6289    22519.46     10.00         4503.89  18015.57
6696    14287.88     10.00            0.00  14287.88
6698    27218.79     10.00         1360.94  25857.85
6909        <NA>     15.00          236.88   2131.87

In [507]:
sales = sales[sales["Discount"] <= 0.40].copy()

In [508]:
sales[sales["Discount"] > 0.40][
    ["GrossSales", "Discount", "DiscountAmount", "NetSales"]
].head(20)

Empty DataFrame
Columns: [GrossSales, Discount, DiscountAmount, NetSales]
Index: []

In [509]:
sales["DiscountAmount"] = (
    sales["GrossSales"] * sales["Discount"]
)

In [510]:
check = np.isclose(
    sales["DiscountAmount"],
    sales["GrossSales"] * sales["Discount"],
    atol=0.01
)

check.all()

np.False_

In [511]:
sales["ExpectedNetSales"] = (
    sales["GrossSales"] - sales["DiscountAmount"]
)

In [512]:
check = np.isclose(
    sales["NetSales"],
    sales["ExpectedNetSales"],
    atol=0.01
)

np.unique(check, return_counts=True)

(array([False,  True]), array([ 1879, 96457]))

In [513]:
sales[sales["NetSales"].isna()]

,OrderItemID,OrderID,ProductID,Quantity,UnitPrice,Discount,GrossSales,DiscountAmount,NetSales,Tax,TotalCost,Profit,ExpectedDiscountAmount,ExpectedNetSales
98,OI00000099,O0008491,P01725,1,856.30,0.10,856.3,85.63,NaN,138.72,607.56,163.11,85.63,770.67
681,OI00000682,O0029929,P01959,1,20952.60,0.15,20952.6,3142.89,NaN,2137.17,12927.54,4882.17,3142.89,17809.71
697,OI00000698,O0030789,P00648,1,2848.62,0.20,2848.62,569.724,NaN,113.95,2141.06,137.84,569.724,2278.896
770,OI00000771,O0013378,P01601,1,1081.37,0.20,1081.37,216.274,NaN,43.26,929.28,-64.18,216.274,865.096
1038,OI00001039,O0014823,P00774,4,8840.88,0.00,35363.52,0.0,NaN,6365.43,17424.76,17938.76,0.0,35363.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98073,OI00098074,O0019494,P00906,2,8357.73,0.10,16715.46,1671.546,NaN,2707.90,13223.28,1820.63,1671.546,15043.914
98182,OI00098183,O0001196,P01121,5,1317.59,0.40,6587.95,2635.18,NaN,474.33,3322.85,629.92,2635.18,3952.77
98347,OI00098348,O0015620,P00847,1,3504.63,0.10,3504.63,350.463,NaN,567.75,2295.78,858.39,350.463,3154.167
98650,OI00098651,O0023007,P00508,1,2261.10,0.30,2261.1,678.33,NaN,284.90,1003.65,579.12,678.33,1582.77
99162,OI00099163,O0014593,P00044,1,5216.61,0.30,5216.61,1564.983,NaN,657.29,3113.21,538.42,1564.983,3651.627

In [514]:
sales["NetSales"] = (
    sales["GrossSales"] - sales["DiscountAmount"]
)

In [515]:
check = np.isclose(
    sales["NetSales"],
    sales["ExpectedNetSales"],
    atol=0.01
)

np.unique(check, return_counts=True)

(array([False,  True]), array([  520, 97816]))

In [516]:
sales["Tax"].isna().sum()

np.int64(244)

In [517]:
(sales["Tax"] < 0).sum()

np.int64(102)

In [518]:
sales[
    ["NetSales", "Tax"]
].head(20)

      NetSales      Tax
0     17275.28  2073.03
1   11677.1245  2101.88
2     10960.14  1972.83
3     11547.81  2078.61
4    13153.648  2367.66
5      3530.37   635.47
6     8761.064   438.05
7      3678.38   183.92
8     1970.555   236.47
9     6574.974  1183.49
10   7792.7645  1402.70
11      3363.7   605.47
12      611.24   110.02
13     13488.8  2427.98
14     2900.61   348.07
15     1560.75   187.29
16   1173.1455   140.78
17    3301.706   594.31
18    4530.152   815.43
19      2849.0   341.88

In [519]:
sales[sales["Tax"].isna()][
    ["NetSales", "Tax"]
].head(20)

         NetSales  Tax
340       8767.77  NaN
944       5774.06  NaN
1521     4818.684  NaN
2028      15901.3  NaN
2805    6415.5495  NaN
4883      586.432  NaN
5366     10811.75  NaN
6084      85928.1  NaN
6499      5234.68  NaN
6757    21165.816  NaN
7438      588.642  NaN
7636    73456.848  NaN
8061     11738.76  NaN
8277      614.227  NaN
8480     1148.835  NaN
8683     1085.776  NaN
9135     1324.215  NaN
10487    9211.296  NaN
10570      551.54  NaN
10968  21985.2325  NaN

In [520]:
sales[sales["Tax"].isna()][
    ["NetSales", "Tax", "TotalCost", "Profit"]
].head(20)

         NetSales  Tax  TotalCost    Profit
340       8767.77  NaN    5919.75   2848.02
944       5774.06  NaN    3428.99   2345.07
1521     4818.684  NaN    3324.51   1494.17
2028      15901.3  NaN   12166.66   3734.64
2805    6415.5495  NaN    3723.18   2692.37
4883      586.432  NaN     620.63    -34.20
5366     10811.75  NaN    7098.30   3713.45
6084      85928.1  NaN   45190.14  40737.96
6499      5234.68  NaN    3204.00   2030.68
6757    21165.816  NaN   17327.81   3838.01
7438      588.642  NaN     362.57    226.07
7636    73456.848  NaN   46033.50  27423.35
8061     11738.76  NaN    7553.04   4185.72
8277      614.227  NaN     390.62    223.61
8480     1148.835  NaN     823.58    325.25
8683     1085.776  NaN     661.84    423.94
9135     1324.215  NaN     973.06    351.16
10487    9211.296  NaN    7419.72   1791.58
10570      551.54  NaN     413.24    138.30
10968  21985.2325  NaN   16473.93   5511.30

In [521]:
sales[sales["Tax"] < 0][
    ["NetSales", "Tax", "TotalCost", "Profit"]
].head(20)

         NetSales   Tax  TotalCost   Profit
694     15066.243 -50.0   12680.10  2386.14
2205      7513.92 -50.0    4080.12  3433.80
2755       278.25 -50.0     163.12   115.13
2894     13212.45 -50.0    8762.10  4450.35
3602     6884.244 -50.0    4806.00  2078.24
3655    3949.5015 -50.0    3068.14   881.36
3912    5149.0705 -50.0    3958.68  1190.39
5775     210.5365 -50.0     161.41    49.13
6568     2354.534 -50.0    1556.92   797.61
8072      1227.52 -50.0    1129.24    98.28
8082      8623.34 -50.0    5434.98  3188.36
8245      955.157 -50.0     689.61   265.55
8328     1048.964 -50.0     831.40   217.56
9309    10975.829 -50.0    6393.52  4582.31
9393      9145.57 -50.0    6880.38  2265.19
11908    11187.18 -50.0    7807.08  3380.10
12764     6214.64 -50.0    3252.78  2961.86
14950     2362.49 -50.0    2015.93   346.56
15632    7302.944 -50.0    6828.24   474.70
16768  13129.8265 -50.0    8906.03  4223.80

In [522]:
sales.loc[sales["Tax"] < 0, "Tax"] = np.nan

In [523]:
(sales["Tax"] < 0).sum()

np.int64(0)

In [524]:
sales["Tax"].isna().sum()

np.int64(346)

In [525]:
sales["TotalCost"].isna().sum()

np.int64(431)

In [526]:
(sales["TotalCost"] < 0).sum()

np.int64(0)

In [527]:
(sales["TotalCost"] == 0).sum()

np.int64(0)

In [528]:
sales[
    ["NetSales", "Tax", "TotalCost", "Profit"]
].head(20)

      NetSales      Tax  TotalCost   Profit
0     17275.28  2073.03    9079.08  8196.20
1   11677.1245  2101.88    8751.62  2925.50
2     10960.14  1972.83   10480.25   479.89
3     11547.81  2078.61    6372.36  5175.45
4    13153.648  2367.66    9885.70  3267.95
5      3530.37   635.47    2736.98   793.39
6     8761.064   438.05    6369.73  2391.33
7      3678.38   183.92    1755.12  1923.26
8     1970.555   236.47    1811.70   158.85
9     6574.974  1183.49    4549.26  2025.71
10   7792.7645  1402.70    4316.54  3476.22
11      3363.7   605.47    2705.66   658.04
12      611.24   110.02     419.94   191.30
13     13488.8  2427.98    9445.10  4043.70
14     2900.61   348.07    2271.69   628.92
15     1560.75   187.29    1267.45   293.30
16   1173.1455   140.78     968.43   204.72
17    3301.706   594.31    1896.08  1405.63
18    4530.152   815.43    3341.89  1188.26
19      2849.0   341.88    2458.64   390.36

In [529]:
sales["ExpectedProfit"] = (
    sales["NetSales"] - sales["TotalCost"]
)

In [530]:
check = np.isclose(
    sales["Profit"],
    sales["ExpectedProfit"],
    atol=0.01
)

np.unique(check, return_counts=True)

(array([False,  True]), array([ 2843, 95493]))

In [531]:
sales["Profit"] = sales["NetSales"] - sales["TotalCost"]

In [532]:
check = np.isclose(
    sales["Profit"],
    sales["NetSales"] - sales["TotalCost"],
    atol=0.01
)

np.unique(check, return_counts=True)

(array([False,  True]), array([  950, 97386]))

In [533]:
(sales["Profit"] < 0).sum()

np.int64(6385)

In [534]:
check = np.isclose(
    sales["Profit"],
    sales["NetSales"] - sales["TotalCost"],
    atol=0.01
)

check[sales["TotalCost"].notna()].all()

np.False_

In [535]:
sales_clean_data = sales.copy()

In [536]:
sales_clean_data

,OrderItemID,OrderID,ProductID,Quantity,UnitPrice,Discount,GrossSales,DiscountAmount,NetSales,Tax,TotalCost,Profit,ExpectedDiscountAmount,ExpectedNetSales,ExpectedProfit
0,OI00000001,O0029046,P00422,4,4318.82,0.00,17275.28,0.0,17275.28,2073.03,9079.08,8196.2,0.0,17275.28,8196.2
1,OI00000002,O0017104,P01523,1,12291.71,0.05,12291.71,614.5855,11677.1245,2101.88,8751.62,2925.5045,614.5855,11677.1245,2925.5045
2,OI00000003,O0000452,P01327,5,3653.38,0.40,18266.9,7306.76,10960.14,1972.83,10480.25,479.89,7306.76,10960.14,479.89
3,OI00000004,O0010615,P01023,1,11547.81,0.00,11547.81,0.0,11547.81,2078.61,6372.36,5175.45,0.0,11547.81,5175.45
4,OI00000005,O0010012,P01086,1,16442.06,0.20,16442.06,3288.412,13153.648,2367.66,9885.70,3267.948,3288.412,13153.648,3267.948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99495,OI00099496,O0013372,P00709,4,10688.56,0.00,42754.24,0.0,42754.24,7695.76,32508.60,10245.64,0.0,42754.24,10245.64
99496,OI00099497,O0022603,P01982,3,7031.25,0.05,21093.75,1054.6875,20039.0625,1001.95,10244.76,9794.3025,1054.6875,20039.0625,9794.3025
99497,OI00099498,O0003190,P01143,1,4070.18,0.00,4070.18,0.0,4070.18,732.63,2118.08,1952.1,0.0,4070.18,1952.1
99498,OI00099499,O0024514,P00766,1,13456.98,0.00,13456.98,0.0,13456.98,1614.84,10205.93,3251.05,0.0,13456.98,3251.05
99499,OI00099500,O0013234,P01945,3,951.61,0.10,2854.83,285.483,2569.347,128.47,1976.07,593.277,285.483,2569.347,593.277

In [537]:
money_columns = [
    "UnitPrice",
    "GrossSales",
    "DiscountAmount",
    "NetSales",
    "Tax",
    "TotalCost",
    "Profit"
]

sales[money_columns] = sales[money_columns].round(2)

In [538]:
sales_clean_data.to_csv("sales_clean_data.csv",index = False)

In [539]:
sales_clean_data = sales.copy()

In [540]:
sales_clean_data

,OrderItemID,OrderID,ProductID,Quantity,UnitPrice,Discount,GrossSales,DiscountAmount,NetSales,Tax,TotalCost,Profit,ExpectedDiscountAmount,ExpectedNetSales,ExpectedProfit
0,OI00000001,O0029046,P00422,4,4318.82,0.00,17275.28,0.0,17275.28,2073.03,9079.08,8196.2,0.0,17275.28,8196.2
1,OI00000002,O0017104,P01523,1,12291.71,0.05,12291.71,614.59,11677.12,2101.88,8751.62,2925.5,614.5855,11677.1245,2925.5045
2,OI00000003,O0000452,P01327,5,3653.38,0.40,18266.9,7306.76,10960.14,1972.83,10480.25,479.89,7306.76,10960.14,479.89
3,OI00000004,O0010615,P01023,1,11547.81,0.00,11547.81,0.0,11547.81,2078.61,6372.36,5175.45,0.0,11547.81,5175.45
4,OI00000005,O0010012,P01086,1,16442.06,0.20,16442.06,3288.41,13153.65,2367.66,9885.70,3267.95,3288.412,13153.648,3267.948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99495,OI00099496,O0013372,P00709,4,10688.56,0.00,42754.24,0.0,42754.24,7695.76,32508.60,10245.64,0.0,42754.24,10245.64
99496,OI00099497,O0022603,P01982,3,7031.25,0.05,21093.75,1054.69,20039.06,1001.95,10244.76,9794.3,1054.6875,20039.0625,9794.3025
99497,OI00099498,O0003190,P01143,1,4070.18,0.00,4070.18,0.0,4070.18,732.63,2118.08,1952.1,0.0,4070.18,1952.1
99498,OI00099499,O0024514,P00766,1,13456.98,0.00,13456.98,0.0,13456.98,1614.84,10205.93,3251.05,0.0,13456.98,3251.05
99499,OI00099500,O0013234,P01945,3,951.61,0.10,2854.83,285.48,2569.35,128.47,1976.07,593.28,285.483,2569.347,593.277

In [541]:
columns = [
    "ExpectedGrossSales",
    "ExpectedDiscountAmount",
    "ExpectedNetSales",
    "ExpectedProfit"
]

sales_clean_data.drop(columns=columns, inplace=True, errors="ignore")

In [542]:
sales_clean_data.to_csv("sales_clean_data.csv",index = False)

In [543]:
products.head()

,ProductID,ProductName,Category,Subcategory,Brand,CostPrice,SellingPrice,Rating
0,P00001,Zenova Outdoor B366,Sports & Fitness,Outdoor,Zenova,1788.18,2507.17,3.9
1,P00002,Echo Footwear C863,Fashion,FOOTWEAR,Echo,845.18,1328.42,4.0
2,P00003,Kairo Non-Fiction D326,Books,Non-Fiction,Kairo,373.60,480.82,4.1
3,P00004,Aster Smartphones E615,Electronics,Smartphones,Aster,11102.85,22999.99,4.0
4,P00005,Echo Bedding F477,Home & Kitchen,Bedding,Echo,1502.75,3092.52,3.9

In [544]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductID     2030 non-null   str
 1   ProductName   2010 non-null   str
 2   Category      2018 non-null   str
 3   Subcategory   2006 non-null   str
 4   Brand         2011 non-null   str
 5   CostPrice     2011 non-null   str
 6   SellingPrice  2010 non-null   str
 7   Rating        1999 non-null   str
dtypes: str(8)
memory usage: 127.0 KB

In [545]:
products["Category"].value_counts()

Category
Electronics         376
Fashion             343
Home & Kitchen      305
Beauty              239
Sports & Fitness    195
Appliances          186
Books               151
Grocery             146
FASHION              17
Home and Kitchen     17
Appliance            15
sports               11
Electrnics            9
electronics           8
Name: count, dtype: int64

In [546]:
products["Category"] = products["Category"].str.title()

In [547]:
products["Category"] = products["Category"].replace("Home And Kitchen","Home & Kitchen")

In [548]:
products["Category"] = products["Category"].replace("sports","Sports & Fitness")

In [549]:
products["Category"] = products["Category"].replace("Electrnics","Electronics")

In [550]:
products["Category"] = products["Category"].replace("Sports","Sports & Fitness")

In [551]:
products["Category"].value_counts()

Category
Electronics         393
Fashion             360
Home & Kitchen      322
Beauty              239
Sports & Fitness    206
Appliances          186
Books               151
Grocery             146
Appliance            15
Name: count, dtype: int64

In [552]:
products["Category"] = products["Category"].replace("Appliance","Appliances")

In [553]:
products["Category"].value_counts()

Category
Electronics         393
Fashion             360
Home & Kitchen      322
Beauty              239
Sports & Fitness    206
Appliances          201
Books               151
Grocery             146
Name: count, dtype: int64

In [554]:
products["Subcategory"].value_counts()

Subcategory
Laptops           84
Headphones        84
Smart Watches     83
Women Clothing    77
Men Clothing      72
                  ..
OUTDOOR            1
smart watches      1
PersonalCare       1
cooling            1
packaged food      1
Name: count, Length: 87, dtype: int64

In [555]:
products["Subcategory"] = products["Subcategory"].str.title()

In [556]:
products["Subcategory"].value_counts()

Subcategory
Laptops                  86
Headphones               84
Smart Watches            84
Women Clothing           81
Men Clothing             74
Footwear                 70
Accessories              70
Bedding                  66
Storage                  66
Bags                     64
Watches                  63
Furniture                61
Home Decor               60
Smartphones              58
Hair Care                57
Cookware                 53
Home Appliances          47
Makeup                   47
Personal Care            46
Skin Care                46
Sportswear               45
Fragrance                44
Packaged Food            43
Yoga                     42
Fitness Equipment        42
Outdoor                  37
Cooling                  37
Children                 37
Kitchen Appliances       37
Non-Fiction              36
Nutrition Accessories    35
Small Appliances         34
Cleaning                 33
Breakfast                33
Academic                 33
Fiction                  32
Snacks                   30
Staples                  28
Business                 26
Beverages                21
Storage                   2
Accessories               2
Sportswear                2
Men Clothing              2
Smart Watches             1
Menclothing               1
Headphones                1
Watches                   1
Cooling                   1
Outdoor                   1
Children                  1
Hair Care                 1
Nutritionaccessories      1
Personalcare              1
Name: count, dtype: int64

In [557]:
products["Subcategory"] = products["Subcategory"].str.strip()

In [558]:
products["Subcategory"].value_counts()

Subcategory
Laptops                  86
Headphones               85
Smart Watches            85
Women Clothing           81
Men Clothing             76
Accessories              72
Footwear                 70
Storage                  68
Bedding                  66
Watches                  64
Bags                     64
Furniture                61
Home Decor               60
Smartphones              58
Hair Care                58
Cookware                 53
Sportswear               47
Home Appliances          47
Makeup                   47
Personal Care            46
Skin Care                46
Fragrance                44
Packaged Food            43
Yoga                     42
Fitness Equipment        42
Outdoor                  38
Cooling                  38
Children                 38
Kitchen Appliances       37
Non-Fiction              36
Nutrition Accessories    35
Small Appliances         34
Cleaning                 33
Breakfast                33
Academic                 33
Fiction                  32
Snacks                   30
Staples                  28
Business                 26
Beverages                21
Menclothing               1
Nutritionaccessories      1
Personalcare              1
Name: count, dtype: int64

In [559]:
products["Subcategory"] = products["Subcategory"].replace({
    "Menclothing": "Men Clothing",
    "Nutritionaccessories": "Nutrition Accessories",
    "Personalcare": "Personal Care"
})

In [560]:
products["ProductName"] = products["ProductName"].str.strip()

In [561]:
products["Brand"] = products["Brand"].str.strip()

In [562]:
products["Brand"] = products["Brand"].str.title()

In [563]:
products["Brand"].value_counts()

Brand
Urbanpeak       123
Mira            107
Nova            106
Zenova          105
Aster           105
Vistara         105
Zenix           104
Solace          103
Nexa            102
Bluearc         102
Kairo           101
Echo             97
Mintleaf         96
Rivon            95
Primenest        95
Cresta           95
Altura           92
Orbito           89
Vertex           88
Luma             84
Unknownbrand     17
Name: count, dtype: int64

In [564]:
products["Brand"] = products["Brand"].replace(
    "Unknownbrand", "Unknown"
)

In [565]:
products.duplicated().sum()

np.int64(30)

In [566]:
products = products.drop_duplicates()

In [567]:
products.duplicated().sum()

np.int64(0)

In [568]:
products.head(5)

,ProductID,ProductName,Category,Subcategory,Brand,CostPrice,SellingPrice,Rating
0,P00001,Zenova Outdoor B366,Sports & Fitness,Outdoor,Zenova,1788.18,2507.17,3.9
1,P00002,Echo Footwear C863,Fashion,Footwear,Echo,845.18,1328.42,4.0
2,P00003,Kairo Non-Fiction D326,Books,Non-Fiction,Kairo,373.60,480.82,4.1
3,P00004,Aster Smartphones E615,Electronics,Smartphones,Aster,11102.85,22999.99,4.0
4,P00005,Echo Bedding F477,Home & Kitchen,Bedding,Echo,1502.75,3092.52,3.9

In [569]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductID     2000 non-null   str
 1   ProductName   1980 non-null   str
 2   Category      1988 non-null   str
 3   Subcategory   1976 non-null   str
 4   Brand         1981 non-null   str
 5   CostPrice     1981 non-null   str
 6   SellingPrice  1980 non-null   str
 7   Rating        1969 non-null   str
dtypes: str(8)
memory usage: 125.1 KB

In [570]:
numeric_cols = ["CostPrice", "SellingPrice", "Rating"]

products[numeric_cols] = products[numeric_cols].apply(
    pd.to_numeric, errors="coerce"
)

In [571]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductID     2000 non-null   str
 1   ProductName   1980 non-null   str
 2   Category      1988 non-null   str
 3   Subcategory   1976 non-null   str
 4   Brand         1981 non-null   str
 5   CostPrice     1951 non-null   float64
 6   SellingPrice  1956 non-null   float64
 7   Rating        1959 non-null   float64
dtypes: float64(3), str(5)
memory usage: 125.1 KB

In [572]:
products[numeric_cols].isnull().sum()

CostPrice       49
SellingPrice    44
Rating          41
dtype: int64

In [573]:
products["Rating"] = products["Rating"].fillna(
    products.groupby("Subcategory")["Rating"].transform("median")
)

In [574]:
products[numeric_cols].isnull().sum()

CostPrice       49
SellingPrice    44
Rating           0
dtype: int64

In [575]:
products[(products["Rating"] < 1) | (products["Rating"] > 5)]

,ProductID,ProductName,Category,Subcategory,Brand,CostPrice,SellingPrice,Rating
25,P00026,Vistara Makeup A528,Beauty,NaN,Vistara,486.09,865.96,0.0
26,P00027,Mira Personal Care B93,Beauty,Personal Care,Mira,1031.66,1501.01,6.2
189,P00190,Solace Nutrition Accessories I199,Sports & Fitness,Nutrition Accessories,Solace,2720.48,3690.21,0.0
237,P00238,Zenix Breakfast E241,Grocery,Breakfast,Zenix,216.27,349.59,6.2
297,P00298,Altura Storage M440,Home & Kitchen,Storage,Altura,1531.65,2659.88,6.2
331,P00332,UrbanPeak Accessories U93,Electronics,Accessories,Urbanpeak,3439.60,6418.26,0.0
375,P00376,zenix bedding m562,Home & Kitchen,Bedding,Zenix,5546.25,7541.56,-1.0
417,P00418,Orbito Packaged Food C946,Grocery,Packaged Food,Orbito,174.95,265.08,0.0
449,P00450,Mira Watches I578,Fashion,Watches,Mira,1468.44,2424.65,6.2
473,P00474,Cresta Men Clothing G835,Fashion,Men Clothing,Cresta,790.46,1216.25,0.0
480,P00481,Nexa Headphones N781,Electronics,Headphones,Nexa,8969.64,11930.53,0.0
521,P00522,Luma Home Decor C670,Home & Kitchen,Home Decor,Luma,3435.95,5431.09,0.0
577,P00578,Rivon Smart Watches G721,Electronics,Smart Watches,Rivon,3322.20,6180.13,0.0
645,P00646,Nexa Headphones W910,Electronics,Headphones,Nexa,9452.45,19831.35,6.2
672,P00673,Cresta Laptops X133,Electronics,Laptops,Cresta,6507.97,8853.40,-1.0
692,P00693,Cresta Personal Care R703,Beauty,Personal Care,Cresta,1054.18,2134.05,-1.0
702,P00703,Mira Fiction B181,Books,Fiction,Mira,376.49,624.90,6.2
729,P00730,Altura Non-Fiction C981,Appliances,Non-Fiction,Altura,476.38,926.60,6.2
824,P00825,Zenix Sportswear T379,Sports & Fitness,Sportswear,Zenix,2512.47,5272.74,-1.0
1060,P01061,Luma Children V741,Books,Children,Luma,713.73,1493.85,6.2
1165,P01166,PrimeNest Bags W52,Fashion,Bags,Primenest,1539.34,2486.38,0.0
1188,P01189,Mira Smart Watches T262,Electronics,Smart Watches,Mira,6399.40,10677.85,0.0
1237,P01238,Nova Hair Care Q592,Beauty,Hair Care,Nova,NaN,1763.97,0.0
1254,P01255,Vistara Makeup H521,Beauty,Makeup,Vistara,693.67,858.37,6.2
1327,P01328,Vistara Bags C480,Fashion,Bags,Vistara,2033.56,3500.30,0.0
1403,P01404,Aster Sportswear A232,Sports & Fitness,Sportswear,Aster,1310.10,2634.46,6.2
1428,P01429,Altura Children Z110,Books,Children,Altura,567.20,819.78,6.2
1466,P01467,Vistara Watches L959,Fashion,Watches,Vistara,547.13,962.65,6.2
1492,P01493,Altura Snacks L746,Grocery,Snacks,Altura,857.96,1066.16,0.0
1498,P01499,Nova Outdoor R118,Sports & Fitness,Outdoor,Nova,2142.77,4394.93,6.2
1531,P01532,Nova Cooling Y196,Appliances,Cooling,Nova,3554.48,6148.61,-1.0
1553,P01554,MintLeaf Furniture U390,Home & Kitchen,Furniture,Mintleaf,2116.36,3152.39,-1.0
1560,P01561,Echo Snacks B69,Grocery,Snacks,Echo,263.85,524.24,0.0
1591,P01592,Cresta Outdoor G527,Sports & Fitness,Outdoor,Cresta,1751.59,3174.90,0.0
1738,P01739,BlueArc Yoga X364,Sports & Fitness,Yoga,Bluearc,1947.83,2735.85,0.0
1782,P01783,UrbanPeak Packaged Food P139,Grocery,Packaged Food,Urbanpeak,400.81,491.82,-1.0
1821,P01822,kairo makeup c279,Beauty,Makeup,Kairo,954.42,1282.56,6.2
1822,P01823,Mira Business D530,Books,Business,Mira,608.94,1265.30,6.2
1842,P01843,Luma Bags X421,Fashion,Bags,Luma,907.74,1230.92,0.0
1859,P01860,UrbanPeak Footwear O633,Fashion,Footwear,Urbanpeak,1435.00,NaN,0.0
1932,P01933,Solace Cleaning J368,Appliances,Cleaning,Solace,2847.21,3826.34,-1.0
1945,P01946,BlueArc Makeup W843,Beauty,Makeup,NaN,276.30,424.56,-1.0
1959,P01960,Nova Watches K516,Fashion,Watches,Nova,1395.51,2342.05,-1.0

In [576]:
products.loc[
    (products["Rating"] < 1) | (products["Rating"] > 5),
    "Rating"
] = np.nan

In [577]:
products["Rating"] = products["Rating"].fillna(
    products.groupby("Subcategory")["Rating"].transform("median")
)

In [578]:
products[
    products["CostPrice"].isnull() | products["SellingPrice"].isnull()
]

,ProductID,ProductName,Category,Subcategory,Brand,CostPrice,SellingPrice,Rating
23,P00024,UrbanPeak Fiction Y45,Books,Fiction,Urbanpeak,645.18,NaN,3.3
54,P00055,UrbanPeak Personal Care D857,Beauty,Personal Care,Urbanpeak,715.75,NaN,3.5
55,P00056,Orbito Smart Watches E155,Electronics,Smart Watches,Orbito,NaN,17266.95,4.2
59,P00060,Aster Fitness Equipment I918,Sports & Fitness,Fitness Equipment,Aster,NaN,2426.63,3.8
128,P00129,Zenova Academic Z242,Books,Academic,Zenova,NaN,285.04,3.7
...,...,...,...,...,...,...,...,...
1872,P01873,Zenova Fiction B46,Books,Fiction,Zenova,376.05,NaN,4.7
1921,P01922,Echo Smart Watches Y390,Electronics,Smart Watches,Echo,9564.23,NaN,4.7
1941,P01942,UrbanPeak Storage S871,Home & Kitchen,Storage,Urbanpeak,NaN,2573.43,3.7
1951,P01952,Cresta-Fitness-Equipment-C645,Sports & Fitness,Fitness Equipment,Cresta,NaN,3381.47,4.3
1970,P01971,BlueArc Laptops V245,Electronics,Laptops,Bluearc,NaN,14939.77,3.8

In [579]:
products["CostPrice"] = products["CostPrice"].fillna(
    products.groupby("Subcategory")["CostPrice"].transform("median")
)

In [580]:
products[
    products["CostPrice"].isnull() | products["SellingPrice"].isnull()
]

,ProductID,ProductName,Category,Subcategory,Brand,CostPrice,SellingPrice,Rating
23,P00024,UrbanPeak Fiction Y45,Books,Fiction,Urbanpeak,645.18,NaN,3.3
54,P00055,UrbanPeak Personal Care D857,Beauty,Personal Care,Urbanpeak,715.75,NaN,3.5
159,P00160,Orbito Packaged Food E477,Grocery,Packaged Food,Orbito,545.21,NaN,4.2
228,P00229,Zenova Outdoor V724,Sports & Fitness,Outdoor,Zenova,1377.10,NaN,4.0
251,P00252,PrimeNest Smart Watches S803,Electronics,Smart Watches,Primenest,5025.06,NaN,3.8
337,P00338,Vistara Makeup A327,Beauty,Makeup,Vistara,890.45,NaN,4.3
428,P00429,Altura Watches N223,Fashion,Watches,Altura,925.93,NaN,3.4
523,P00524,Kairo Non-Fiction E590,Books,Non-Fiction,Kairo,490.31,NaN,4.5
524,P00525,Vistara Headphones F588,Electronics,Headphones,Vistara,2558.57,NaN,3.7
563,P00564,Luma Cookware S446,Home & Kitchen,Cookware,Luma,1107.33,NaN,3.8
565,P00566,Vistara Home Appliances U337,Appliances,Home Appliances,Vistara,5851.56,NaN,4.1
581,P00582,PrimeNest Laptops K115,Electronics,Laptops,Primenest,6168.04,NaN,4.5
596,P00597,UrbanPeak Cookware Z25,Home & Kitchen,Cookware,Urbanpeak,3759.52,NaN,4.2
649,P00650,Vistara Bags A678,Fashion,Bags,Vistara,1002.19,NaN,4.2
709,P00710,Zenova Smart Watches I839,Electronics,Smart Watches,Zenova,7266.99,NaN,4.8
714,P00715,Mira Smartphones N82,Electronics,Smartphones,Mira,4286.28,NaN,4.4
744,P00745,UrbanPeak Smart Watches R631,Electronics,Smart Watches,Urbanpeak,10481.32,NaN,3.3
758,P00759,Zenix Men Clothing F470,Fashion,Men Clothing,Zenix,790.87,NaN,3.7
776,P00777,Luma Breakfast X126,Grocery,Breakfast,Luma,156.85,NaN,3.4
785,P00786,Zenix Yoga G609,Sports & Fitness,Yoga,Zenix,1936.94,NaN,4.5
797,P00798,BlueArc Non-Fiction S352,Books,Non-Fiction,Bluearc,314.30,NaN,4.1
834,P00835,UrbanPeak Bedding D873,Home & Kitchen,Bedding,Urbanpeak,2498.72,NaN,4.2
881,P00882,Vistara Footwear Y215,Fashion,Footwear,Vistara,0.00,NaN,3.5
905,P00906,MintLeaf Headphones W419,Electronics,Headphones,Mintleaf,6611.64,NaN,3.9
945,P00946,MintLeaf Cookware K487,Home & Kitchen,Cookware,Mintleaf,2663.89,NaN,3.8
972,P00973,PrimeNest Cleaning L546,Appliances,Cleaning,Primenest,4857.95,NaN,4.6
1015,P01016,Nexa Cookware C121,Home & Kitchen,Cookware,Nexa,1533.02,NaN,3.8
1099,P01100,Aster Skin Care I566,Beauty,Skin Care,Aster,587.46,NaN,4.5
1135,P01136,PrimeNest Home Decor S37,Home & Kitchen,Home Decor,Primenest,2188.79,NaN,4.4
1208,P01209,Orbito Academic N750,Fashion,Academic,Orbito,821.00,NaN,3.7
1271,P01272,Vistara Hair Care Y920,Beauty,Hair Care,Unknown,592.47,NaN,3.8
1457,P01458,Aster Footwear C822,Fashion,Footwear,Aster,1239.71,NaN,3.0
1491,P01492,Cresta Home Decor K614,Home & Kitchen,Home Decor,Cresta,6601.79,NaN,3.9
1511,P01512,Luma Nutrition Accessories E916,Sports & Fitness,Nutrition Accessories,Luma,1560.52,NaN,3.1
1617,P01618,Kairo Watches G497,Fashion,Watches,Kairo,1084.99,NaN,4.5
1674,P01675,Altura Sportswear L89,Sports & Fitness,Sportswear,Altura,5514.02,NaN,4.7
1676,P01677,Rivon Smartphones N963,Electronics,Smartphones,Rivon,10253.88,NaN,3.5
1722,P01723,Cresta Bedding H257,Home & Kitchen,Bedding,Cresta,2228.61,NaN,4.8
1792,P01793,UrbanPeak Skin Care Z727,Beauty,Skin Care,Urbanpeak,756.55,NaN,2.9
1836,P01837,Echo Beverages R33,Grocery,NaN,Echo,148.87,NaN,4.4
1855,P01856,UrbanPeak Fitness Equipment K234,Sports & Fitness,Fitness Equipment,Urbanpeak,1777.49,NaN,3.9
1859,P01860,UrbanPeak Footwear O633,Fashion,Footwear,Urbanpeak,1435.00,NaN,3.9
1872,P01873,Zenova Fiction B46,Books,Fiction,Zenova,376.05,NaN,4.7
1921,P01922,Echo Smart Watches Y390,Electronics,Smart Watches,Echo,9564.23,NaN,4.7

In [581]:
products["CostPrice"] = products["CostPrice"].fillna(
    products["CostPrice"].median()
)

In [582]:
products["SellingPrice"] = products["SellingPrice"].fillna(
    products.groupby("Subcategory")["SellingPrice"].transform("median")
)

In [583]:
products["SellingPrice"] = products["SellingPrice"].fillna(
    products["SellingPrice"].median()
)

In [584]:
products[["CostPrice", "SellingPrice"]].isnull().sum()

CostPrice       0
SellingPrice    0
dtype: int64

In [585]:
(products["CostPrice"] < 0).sum()

np.int64(17)

In [586]:
products.loc[products["CostPrice"] < 0, "CostPrice"] = np.nan

In [587]:
products["CostPrice"] = products["CostPrice"].fillna(
    products.groupby("Subcategory")["CostPrice"].transform("median")
)

In [588]:
(products["CostPrice"] < 0).sum()

np.int64(0)

In [589]:
(products["SellingPrice"] < 0).sum()

np.int64(15)

In [590]:
products.loc[products["SellingPrice"] < 0, "SellingPrice"] = np.nan

In [591]:
products["SellingPrice"] = products["SellingPrice"].fillna(
    products.groupby("Subcategory")["SellingPrice"].transform("median")
)

In [592]:
(products["SellingPrice"] < 0).sum()

np.int64(0)

In [593]:
products[["Brand", "ProductName","Category","Subcategory",]].isnull().sum()

Brand          19
ProductName    20
Category       12
Subcategory    24
dtype: int64

In [594]:
products["Brand"] = products["Brand"].fillna("Unknown")

In [595]:
products["ProductName"] = products["ProductName"].fillna("Unknown")

In [598]:
products["Category"] = products["Category"].fillna("Unknown")

In [596]:
products["Subcategory"] = products["Subcategory"].fillna("Unknown")

In [599]:
products[["Brand", "ProductName","Category","Subcategory",]].isnull().sum()

Brand          0
ProductName    0
Category       0
Subcategory    0
dtype: int64

In [600]:
products["ProductID"].isna().sum()

np.int64(0)

In [603]:
products["CostPrice"] = products["CostPrice"].round(2)
products["SellingPrice"] = products["SellingPrice"].round(2)
products["Rating"] = products["Rating"].round(1)

In [604]:
products_clean_data = products.copy()

In [605]:
products_clean_data.to_csv("products_clean_data.csv", index = False)